-- insert into calc (id,number1,number2,countofnumbers) values (1,2,5,7);
-- insert into calc (id,number1,number2,countofnumbers) values (2,8,10,18);
--
-- insert into fruit (id,name,season) values (1,'Apple','Summer');
-- insert into fruit (id,name,season) values (2,'Orange','Winter');
-- insert into fruit (id,name,season) values (3,'Tomato','Summer');
-- insert into fruit (id,name,season) values (4,'Watermelon','Winter');
-- insert into fruit (id,name,season) values (5,'Peach','Summer');
-- insert into fruit (id,name,season) values (6,'Black Currant','Winter');
-- insert into fruit (id,name,season) values (7,'Apple','Summer');
-- insert into fruit (id,name,season) values (8,'Orange','Winter');
